use std::fmt::Write;

use crate::emit_gpui::SEMANTIC_MAPPING;
use crate::{ProseHighlightStyle, TokenSet, PROSE_CAPTURES};

impl TokenSet {
    #[must_use]
    pub fn emit_css(&self) -> String {
        let mut output =
            String::from("/* Generated by theorem-design-core. Do not edit. */\n:root {\n");
        for path in self.token_paths() {
            let Ok(value) = self.css_value(path) else {
                continue;
            };
            let _ = writeln!(output, "  --{}: {value};", css_token_name(path));
        }
        for (semantic, path) in SEMANTIC_MAPPING {
            let _ = writeln!(
                output,
                "  --{}: var(--{});",
                semantic.replace('_', "-"),
                css_token_name(path)
            );
        }
        output.push_str("}\n\n");
        output.push_str(
            "[data-actor=\"human\"] { font-family: var(--font-human); }\n\
             [data-actor=\"agent\"] { font-family: var(--font-agent); }\n\
             [data-actor=\"human\"] .actor-accent { color: var(--human-500); background: none; }\n\
             [data-actor=\"agent\"] .actor-accent { color: var(--agent-500); }\n\
             .actor-commit { color: var(--human-900); }\n\
             .insight { color: var(--insight-gold); }\n\n",
        );
        for capture in PROSE_CAPTURES {
            let style = self
                .prose_highlight_style(capture)
                .unwrap_or_else(|| panic!("prose capture {capture} must resolve"));
            let _ = write!(
                output,
                ".prose-capture-{} {{",
                capture.trim_start_matches("prose.").replace('.', "-")
            );
            emit_prose_declarations(&mut output, style);
            output.push_str(" }\n");
        }
        output
    }
}

fn css_token_name(path: &str) -> String {
    let path = path
        .strip_prefix("color.")
        .or_else(|| path.strip_prefix("typography."))
        .unwrap_or(path);
    let mut name = String::with_capacity(path.len());
    for character in path.chars() {
        if character == '.' {
            name.push('-');
        } else if character.is_ascii_uppercase() {
            name.push('-');
            name.push(character.to_ascii_lowercase());
        } else {
            name.push(character);
        }
    }
    name
}

fn emit_prose_declarations(output: &mut String, style: ProseHighlightStyle) {
    if let Some(color) = style.foreground {
        let _ = write!(output, " color: {};", color.hex());
    }
    if let Some(color) = style.background {
        let _ = write!(output, " background-color: {};", color.hex());
    }
    if style.underline {
        output.push_str(" text-decoration-line: underline;");
        output.push_str(" text-decoration-style: dotted;");
    }
    if let Some(weight) = style.font_weight {
        let _ = write!(output, " font-weight: {weight};");
    }
}
